version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: flynest_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flynest
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
